[phases]
  setup = { commands = ["go install"] }
  install = { commands = ["go mod download"] }
  build = { commands = ["go build -o out"] }
  start = { commands = ["./out"] }

[build]
  language = "go"