[phases]
  setup = { commands = ["go mod download"] }
  build = { commands = ["go build -o /app/out main.go db.go models.go handlers.go redis.go"] }
  start = { commands = ["/app/out"] }

[build]
  language = "go"