[phases.setup]
commands = [
  "go mod download"
]

[phases.build]
commands = [
  "go build -o app main.go db.go models.go handlers.go redis.go"
]

[phases.start]
commands = [
  "chmod +x app",  # Ensures the binary has execution permissions
  "./app"  # Runs the built Go application
]