[phases]
  setup = { commands = ["go install"] }
  install = { commands = ["go mod download"] }
  build = { commands = ["go build -o out main.go db.go models.go handlers.go redis.go"] }
  start = { commands = ["./out"] }

[build]
  language = "go"